[package]
name = "editor"
version = "0.1.0"
authors = ["Michael Zhang <mail@mzhang.io>"]
edition = "2018"

[workspace]
members = [
    "bass-sys",
]

[dependencies]
anyhow = "1.0.37"
bass-sys = { path = "bass-sys" }
ggez = "0.5.1"
libosu = "0.0.11"
log = "0.4.11"
stderrlog = "0.5.0"
