[package]
name = "editor"
version = "0.1.0"
authors = ["Michael Zhang <mail@mzhang.io>"]
edition = "2018"

[profile.release]
debug = true

[workspace]
members = [
    "bass-sys",
]

[dependencies]
anyhow = "1.0.37"
bass-sys = { path = "bass-sys" }
ggez = "0.5.1"
log = "0.4.11"
stderrlog = "0.5.0"
num = "0.3.1"
ordered-float = "2.0.1"
structopt = "0.3.21"

[dependencies.libosu]
git = "https://github.com/iptq/libosu"
rev = "7fbe7afbad55b25398062719ebaccbff0387d139"
