on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: editor.exe
          path: target/release/editor.exe

# vim: set ts=2 tw=2 sw=2 et :
