on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      # Check out code
      - uses: actions/checkout@v2
        with:
          path: editor
      - uses: actions/checkout@v2
        with:
          repository: iptq/libosu
          path: libosu

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: build
        working-directory: editor
        run: |
          cargo build --release

      - uses: actions/upload-artifact@v2
        working-directory: editor
        with:
          name: editor.exe
          path: target/release/editor.exe

# vim: set ts=2 tw=2 sw=2 et :
